# Generated by Django 3.2.5 on 2021-07-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contactrequests_الأسم'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequests',
            name='الأسم',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
