# Generated by Django 3.2.5 on 2021-07-30 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contactrequests_الأسم'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOfBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الأسم', models.CharField(blank=True, max_length=255, null=True)),
                ('الوصف', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الأسم', models.CharField(blank=True, max_length=255, null=True)),
                ('اللينك', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.categoryofbusiness')),
            ],
        ),
    ]
