# Generated by Django 3.2.5 on 2021-07-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210730_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
